name: Download File

env:
  url: https://dl.pstmn.io/download/version/10.13.6/win64
  file_name: postman-10.13.6.exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download File
      run: |
        wget -O ${{ env.file_name }} ${{ env.url }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.file_name }}
        release_name: ${{ env.file_name }}
        body: |
          ${{ env.file_name }}

    - name: Upload File
      id: upload_file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.file_name }}
        asset_name: ${{ env.file_name }}
        asset_content_type: application/octet-stream
